### ISSUE TITLE
Scalad dependency in build.sbt

### ISSUE THREAD

**Issue by switzer** [eigengo/akka-patterns#10]
Hi - sbt is not finding scalad.  I updated the resolvers to fix:

resolvers += "cakesolutions local repo" at "http://build.cakesolutions.net/artifactory/libs-release-local"

resolvers += "cakesolutions local snapshots" at "http://build.cakesolutions.net/artifactory/libs-snapshot-local"

Thanks for this great new code!

**Comment by fommil** [comment]
This should be in sonatype or maven central at some point, tracked here https://github.com/janm399/scalad/issues/60
