### ISSUE TITLE
MongoDB/ScalaD pattern

### ISSUE THREAD

**Issue by switzer** [eigengo/akka-patterns#11]
Hi -

I would love to see this project connect to MongoDB (what you had here before), in addition to neo4j

Thanks!

**Comment by janm399** [comment]
It is coming--hang in there!

**Comment by fommil** [comment]
Should show:
- production / test setup
- marshalling
- simple CRUD
- indexing
- use of DSL (e.g. for a `$set`)
- aggregation

**Comment by fommil** [comment]
Depends on https://github.com/janm399/scalad/issues/51

**Comment by fommil** [comment]
actually, this depends on https://github.com/janm399/scalad/issues/64

**Comment by fommil** [comment]
No longer blocked :-D

**Comment by fommil** [comment]
@switzer if you want to see some good usage of mongodb (via scalad), then have a look here https://github.com/fommil/scalad/blob/master/src/test/scala/org/cakesolutions/scalad/mongo/sprayjson/PersistenceSpec.scala which will be merged into the master repo soon.
