### ISSUE TITLE
IOBridge changes with Spray version 1.1-M6

### ISSUE THREAD

**Issue by switzer** [eigengo/akka-patterns#8]
the IOBridge no longer has start() and stop(), and it is created differently in web/boot.scala.

I will try to make a pull request for this - but it may take me a bit to get it prepared.

**Comment by janm399** [comment]
I actually already have the code in another project.

``` scala
  val ioBridge = IOExtension(actorSystem).ioBridge
```

And I've also modified the structure of the various boot files. I will try my best to get a major update in, but it'll be a few more days still.

**Comment by switzer** [comment]
Sounds good.  I fixed all of the issues from what is currently in github, and created a few more tests.  There were issues with inserting data, as well as with the address field.  I am afraid that I have made too many changes for a simple pull request.  I will look forward to your changes, and merge those with my changes and enhancements, so that you can accept my changes back after your update if you wish.

Thanks

**Comment by janm399** [comment]
All fixed; we're on the latest nightly spray.
